// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/service.proto

package genconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	gen "github.com/Meedoeed/ssh-sync-automation/internal/gen"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackendServiceName is the fully-qualified name of the BackendService service.
	BackendServiceName = "rpc.BackendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackendServiceRegisterWorkerProcedure is the fully-qualified name of the BackendService's
	// RegisterWorker RPC.
	BackendServiceRegisterWorkerProcedure = "/rpc.BackendService/RegisterWorker"
	// BackendServiceHeartbeatProcedure is the fully-qualified name of the BackendService's Heartbeat
	// RPC.
	BackendServiceHeartbeatProcedure = "/rpc.BackendService/Heartbeat"
	// BackendServiceGetTaskProcedure is the fully-qualified name of the BackendService's GetTask RPC.
	BackendServiceGetTaskProcedure = "/rpc.BackendService/GetTask"
	// BackendServiceUpdateTaskProgressProcedure is the fully-qualified name of the BackendService's
	// UpdateTaskProgress RPC.
	BackendServiceUpdateTaskProgressProcedure = "/rpc.BackendService/UpdateTaskProgress"
	// BackendServiceCompleteTaskProcedure is the fully-qualified name of the BackendService's
	// CompleteTask RPC.
	BackendServiceCompleteTaskProcedure = "/rpc.BackendService/CompleteTask"
	// BackendServiceFailTaskProcedure is the fully-qualified name of the BackendService's FailTask RPC.
	BackendServiceFailTaskProcedure = "/rpc.BackendService/FailTask"
	// BackendServiceCreateTaskProcedure is the fully-qualified name of the BackendService's CreateTask
	// RPC.
	BackendServiceCreateTaskProcedure = "/rpc.BackendService/CreateTask"
	// BackendServiceGetServersProcedure is the fully-qualified name of the BackendService's GetServers
	// RPC.
	BackendServiceGetServersProcedure = "/rpc.BackendService/GetServers"
	// BackendServiceGetServerProcedure is the fully-qualified name of the BackendService's GetServer
	// RPC.
	BackendServiceGetServerProcedure = "/rpc.BackendService/GetServer"
	// BackendServiceCheckTaskExistsProcedure is the fully-qualified name of the BackendService's
	// CheckTaskExists RPC.
	BackendServiceCheckTaskExistsProcedure = "/rpc.BackendService/CheckTaskExists"
	// BackendServiceTryBecomeLeaderProcedure is the fully-qualified name of the BackendService's
	// TryBecomeLeader RPC.
	BackendServiceTryBecomeLeaderProcedure = "/rpc.BackendService/TryBecomeLeader"
	// BackendServiceRenewLeadershipProcedure is the fully-qualified name of the BackendService's
	// RenewLeadership RPC.
	BackendServiceRenewLeadershipProcedure = "/rpc.BackendService/RenewLeadership"
	// BackendServiceReleaseLeadershipProcedure is the fully-qualified name of the BackendService's
	// ReleaseLeadership RPC.
	BackendServiceReleaseLeadershipProcedure = "/rpc.BackendService/ReleaseLeadership"
	// BackendServiceGetLeaderProcedure is the fully-qualified name of the BackendService's GetLeader
	// RPC.
	BackendServiceGetLeaderProcedure = "/rpc.BackendService/GetLeader"
	// BackendServiceListServersProcedure is the fully-qualified name of the BackendService's
	// ListServers RPC.
	BackendServiceListServersProcedure = "/rpc.BackendService/ListServers"
	// BackendServiceGetServerByIdProcedure is the fully-qualified name of the BackendService's
	// GetServerById RPC.
	BackendServiceGetServerByIdProcedure = "/rpc.BackendService/GetServerById"
	// BackendServiceCreateServerProcedure is the fully-qualified name of the BackendService's
	// CreateServer RPC.
	BackendServiceCreateServerProcedure = "/rpc.BackendService/CreateServer"
	// BackendServiceUpdateServerProcedure is the fully-qualified name of the BackendService's
	// UpdateServer RPC.
	BackendServiceUpdateServerProcedure = "/rpc.BackendService/UpdateServer"
	// BackendServiceDeleteServerProcedure is the fully-qualified name of the BackendService's
	// DeleteServer RPC.
	BackendServiceDeleteServerProcedure = "/rpc.BackendService/DeleteServer"
	// BackendServiceListTasksProcedure is the fully-qualified name of the BackendService's ListTasks
	// RPC.
	BackendServiceListTasksProcedure = "/rpc.BackendService/ListTasks"
	// BackendServiceGetTaskByIdProcedure is the fully-qualified name of the BackendService's
	// GetTaskById RPC.
	BackendServiceGetTaskByIdProcedure = "/rpc.BackendService/GetTaskById"
	// BackendServiceGetWorkerStatsProcedure is the fully-qualified name of the BackendService's
	// GetWorkerStats RPC.
	BackendServiceGetWorkerStatsProcedure = "/rpc.BackendService/GetWorkerStats"
	// BackendServiceHealthCheckProcedure is the fully-qualified name of the BackendService's
	// HealthCheck RPC.
	BackendServiceHealthCheckProcedure = "/rpc.BackendService/HealthCheck"
	// BackendServiceGetProbeTaskProcedure is the fully-qualified name of the BackendService's
	// GetProbeTask RPC.
	BackendServiceGetProbeTaskProcedure = "/rpc.BackendService/GetProbeTask"
	// BackendServiceReportProbeResultProcedure is the fully-qualified name of the BackendService's
	// ReportProbeResult RPC.
	BackendServiceReportProbeResultProcedure = "/rpc.BackendService/ReportProbeResult"
)

// BackendServiceClient is a client for the rpc.BackendService service.
type BackendServiceClient interface {
	RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error)
	Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error)
	GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error)
	UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error)
	CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error)
	FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error)
	CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error)
	GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error)
	GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error)
	CheckTaskExists(context.Context, *connect.Request[gen.CheckTaskExistsRequest]) (*connect.Response[gen.CheckTaskExistsResponse], error)
	TryBecomeLeader(context.Context, *connect.Request[gen.TryBecomeLeaderRequest]) (*connect.Response[gen.TryBecomeLeaderResponse], error)
	RenewLeadership(context.Context, *connect.Request[gen.RenewLeadershipRequest]) (*connect.Response[gen.RenewLeadershipResponse], error)
	ReleaseLeadership(context.Context, *connect.Request[gen.ReleaseLeadershipRequest]) (*connect.Response[gen.ReleaseLeadershipResponse], error)
	GetLeader(context.Context, *connect.Request[gen.GetLeaderRequest]) (*connect.Response[gen.GetLeaderResponse], error)
	ListServers(context.Context, *connect.Request[gen.ListServersRequest]) (*connect.Response[gen.ListServersResponse], error)
	GetServerById(context.Context, *connect.Request[gen.GetServerByIdRequest]) (*connect.Response[gen.GetServerByIdResponse], error)
	CreateServer(context.Context, *connect.Request[gen.CreateServerRequest]) (*connect.Response[gen.CreateServerResponse], error)
	UpdateServer(context.Context, *connect.Request[gen.UpdateServerRequest]) (*connect.Response[gen.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[gen.DeleteServerRequest]) (*connect.Response[gen.DeleteServerResponse], error)
	ListTasks(context.Context, *connect.Request[gen.ListTasksRequest]) (*connect.Response[gen.ListTasksResponse], error)
	GetTaskById(context.Context, *connect.Request[gen.GetTaskByIdRequest]) (*connect.Response[gen.GetTaskByIdResponse], error)
	GetWorkerStats(context.Context, *connect.Request[gen.GetWorkerStatsRequest]) (*connect.Response[gen.GetWorkerStatsResponse], error)
	HealthCheck(context.Context, *connect.Request[gen.HealthCheckRequest]) (*connect.Response[gen.HealthCheckResponse], error)
	GetProbeTask(context.Context, *connect.Request[gen.GetProbeTaskRequest]) (*connect.Response[gen.GetProbeTaskResponse], error)
	ReportProbeResult(context.Context, *connect.Request[gen.ReportProbeResultRequest]) (*connect.Response[gen.ReportProbeResultResponse], error)
}

// NewBackendServiceClient constructs a client for the rpc.BackendService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backendServiceMethods := gen.File_proto_service_proto.Services().ByName("BackendService").Methods()
	return &backendServiceClient{
		registerWorker: connect.NewClient[gen.RegisterWorkerRequest, gen.RegisterWorkerResponse](
			httpClient,
			baseURL+BackendServiceRegisterWorkerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("RegisterWorker")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[gen.HeartbeatRequest, gen.HeartbeatResponse](
			httpClient,
			baseURL+BackendServiceHeartbeatProcedure,
			connect.WithSchema(backendServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[gen.GetTaskRequest, gen.GetTaskResponse](
			httpClient,
			baseURL+BackendServiceGetTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		updateTaskProgress: connect.NewClient[gen.UpdateProgressRequest, gen.UpdateProgressResponse](
			httpClient,
			baseURL+BackendServiceUpdateTaskProgressProcedure,
			connect.WithSchema(backendServiceMethods.ByName("UpdateTaskProgress")),
			connect.WithClientOptions(opts...),
		),
		completeTask: connect.NewClient[gen.CompleteTaskRequest, gen.CompleteTaskResponse](
			httpClient,
			baseURL+BackendServiceCompleteTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CompleteTask")),
			connect.WithClientOptions(opts...),
		),
		failTask: connect.NewClient[gen.FailTaskRequest, gen.FailTaskResponse](
			httpClient,
			baseURL+BackendServiceFailTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("FailTask")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[gen.CreateTaskRequest, gen.CreateTaskResponse](
			httpClient,
			baseURL+BackendServiceCreateTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getServers: connect.NewClient[gen.GetServersRequest, gen.GetServersResponse](
			httpClient,
			baseURL+BackendServiceGetServersProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetServers")),
			connect.WithClientOptions(opts...),
		),
		getServer: connect.NewClient[gen.GetServerRequest, gen.GetServerResponse](
			httpClient,
			baseURL+BackendServiceGetServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
		checkTaskExists: connect.NewClient[gen.CheckTaskExistsRequest, gen.CheckTaskExistsResponse](
			httpClient,
			baseURL+BackendServiceCheckTaskExistsProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CheckTaskExists")),
			connect.WithClientOptions(opts...),
		),
		tryBecomeLeader: connect.NewClient[gen.TryBecomeLeaderRequest, gen.TryBecomeLeaderResponse](
			httpClient,
			baseURL+BackendServiceTryBecomeLeaderProcedure,
			connect.WithSchema(backendServiceMethods.ByName("TryBecomeLeader")),
			connect.WithClientOptions(opts...),
		),
		renewLeadership: connect.NewClient[gen.RenewLeadershipRequest, gen.RenewLeadershipResponse](
			httpClient,
			baseURL+BackendServiceRenewLeadershipProcedure,
			connect.WithSchema(backendServiceMethods.ByName("RenewLeadership")),
			connect.WithClientOptions(opts...),
		),
		releaseLeadership: connect.NewClient[gen.ReleaseLeadershipRequest, gen.ReleaseLeadershipResponse](
			httpClient,
			baseURL+BackendServiceReleaseLeadershipProcedure,
			connect.WithSchema(backendServiceMethods.ByName("ReleaseLeadership")),
			connect.WithClientOptions(opts...),
		),
		getLeader: connect.NewClient[gen.GetLeaderRequest, gen.GetLeaderResponse](
			httpClient,
			baseURL+BackendServiceGetLeaderProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetLeader")),
			connect.WithClientOptions(opts...),
		),
		listServers: connect.NewClient[gen.ListServersRequest, gen.ListServersResponse](
			httpClient,
			baseURL+BackendServiceListServersProcedure,
			connect.WithSchema(backendServiceMethods.ByName("ListServers")),
			connect.WithClientOptions(opts...),
		),
		getServerById: connect.NewClient[gen.GetServerByIdRequest, gen.GetServerByIdResponse](
			httpClient,
			baseURL+BackendServiceGetServerByIdProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetServerById")),
			connect.WithClientOptions(opts...),
		),
		createServer: connect.NewClient[gen.CreateServerRequest, gen.CreateServerResponse](
			httpClient,
			baseURL+BackendServiceCreateServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CreateServer")),
			connect.WithClientOptions(opts...),
		),
		updateServer: connect.NewClient[gen.UpdateServerRequest, gen.UpdateServerResponse](
			httpClient,
			baseURL+BackendServiceUpdateServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("UpdateServer")),
			connect.WithClientOptions(opts...),
		),
		deleteServer: connect.NewClient[gen.DeleteServerRequest, gen.DeleteServerResponse](
			httpClient,
			baseURL+BackendServiceDeleteServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("DeleteServer")),
			connect.WithClientOptions(opts...),
		),
		listTasks: connect.NewClient[gen.ListTasksRequest, gen.ListTasksResponse](
			httpClient,
			baseURL+BackendServiceListTasksProcedure,
			connect.WithSchema(backendServiceMethods.ByName("ListTasks")),
			connect.WithClientOptions(opts...),
		),
		getTaskById: connect.NewClient[gen.GetTaskByIdRequest, gen.GetTaskByIdResponse](
			httpClient,
			baseURL+BackendServiceGetTaskByIdProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetTaskById")),
			connect.WithClientOptions(opts...),
		),
		getWorkerStats: connect.NewClient[gen.GetWorkerStatsRequest, gen.GetWorkerStatsResponse](
			httpClient,
			baseURL+BackendServiceGetWorkerStatsProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetWorkerStats")),
			connect.WithClientOptions(opts...),
		),
		healthCheck: connect.NewClient[gen.HealthCheckRequest, gen.HealthCheckResponse](
			httpClient,
			baseURL+BackendServiceHealthCheckProcedure,
			connect.WithSchema(backendServiceMethods.ByName("HealthCheck")),
			connect.WithClientOptions(opts...),
		),
		getProbeTask: connect.NewClient[gen.GetProbeTaskRequest, gen.GetProbeTaskResponse](
			httpClient,
			baseURL+BackendServiceGetProbeTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetProbeTask")),
			connect.WithClientOptions(opts...),
		),
		reportProbeResult: connect.NewClient[gen.ReportProbeResultRequest, gen.ReportProbeResultResponse](
			httpClient,
			baseURL+BackendServiceReportProbeResultProcedure,
			connect.WithSchema(backendServiceMethods.ByName("ReportProbeResult")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backendServiceClient implements BackendServiceClient.
type backendServiceClient struct {
	registerWorker     *connect.Client[gen.RegisterWorkerRequest, gen.RegisterWorkerResponse]
	heartbeat          *connect.Client[gen.HeartbeatRequest, gen.HeartbeatResponse]
	getTask            *connect.Client[gen.GetTaskRequest, gen.GetTaskResponse]
	updateTaskProgress *connect.Client[gen.UpdateProgressRequest, gen.UpdateProgressResponse]
	completeTask       *connect.Client[gen.CompleteTaskRequest, gen.CompleteTaskResponse]
	failTask           *connect.Client[gen.FailTaskRequest, gen.FailTaskResponse]
	createTask         *connect.Client[gen.CreateTaskRequest, gen.CreateTaskResponse]
	getServers         *connect.Client[gen.GetServersRequest, gen.GetServersResponse]
	getServer          *connect.Client[gen.GetServerRequest, gen.GetServerResponse]
	checkTaskExists    *connect.Client[gen.CheckTaskExistsRequest, gen.CheckTaskExistsResponse]
	tryBecomeLeader    *connect.Client[gen.TryBecomeLeaderRequest, gen.TryBecomeLeaderResponse]
	renewLeadership    *connect.Client[gen.RenewLeadershipRequest, gen.RenewLeadershipResponse]
	releaseLeadership  *connect.Client[gen.ReleaseLeadershipRequest, gen.ReleaseLeadershipResponse]
	getLeader          *connect.Client[gen.GetLeaderRequest, gen.GetLeaderResponse]
	listServers        *connect.Client[gen.ListServersRequest, gen.ListServersResponse]
	getServerById      *connect.Client[gen.GetServerByIdRequest, gen.GetServerByIdResponse]
	createServer       *connect.Client[gen.CreateServerRequest, gen.CreateServerResponse]
	updateServer       *connect.Client[gen.UpdateServerRequest, gen.UpdateServerResponse]
	deleteServer       *connect.Client[gen.DeleteServerRequest, gen.DeleteServerResponse]
	listTasks          *connect.Client[gen.ListTasksRequest, gen.ListTasksResponse]
	getTaskById        *connect.Client[gen.GetTaskByIdRequest, gen.GetTaskByIdResponse]
	getWorkerStats     *connect.Client[gen.GetWorkerStatsRequest, gen.GetWorkerStatsResponse]
	healthCheck        *connect.Client[gen.HealthCheckRequest, gen.HealthCheckResponse]
	getProbeTask       *connect.Client[gen.GetProbeTaskRequest, gen.GetProbeTaskResponse]
	reportProbeResult  *connect.Client[gen.ReportProbeResultRequest, gen.ReportProbeResultResponse]
}

// RegisterWorker calls rpc.BackendService.RegisterWorker.
func (c *backendServiceClient) RegisterWorker(ctx context.Context, req *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error) {
	return c.registerWorker.CallUnary(ctx, req)
}

// Heartbeat calls rpc.BackendService.Heartbeat.
func (c *backendServiceClient) Heartbeat(ctx context.Context, req *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// GetTask calls rpc.BackendService.GetTask.
func (c *backendServiceClient) GetTask(ctx context.Context, req *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// UpdateTaskProgress calls rpc.BackendService.UpdateTaskProgress.
func (c *backendServiceClient) UpdateTaskProgress(ctx context.Context, req *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error) {
	return c.updateTaskProgress.CallUnary(ctx, req)
}

// CompleteTask calls rpc.BackendService.CompleteTask.
func (c *backendServiceClient) CompleteTask(ctx context.Context, req *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error) {
	return c.completeTask.CallUnary(ctx, req)
}

// FailTask calls rpc.BackendService.FailTask.
func (c *backendServiceClient) FailTask(ctx context.Context, req *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error) {
	return c.failTask.CallUnary(ctx, req)
}

// CreateTask calls rpc.BackendService.CreateTask.
func (c *backendServiceClient) CreateTask(ctx context.Context, req *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// GetServers calls rpc.BackendService.GetServers.
func (c *backendServiceClient) GetServers(ctx context.Context, req *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error) {
	return c.getServers.CallUnary(ctx, req)
}

// GetServer calls rpc.BackendService.GetServer.
func (c *backendServiceClient) GetServer(ctx context.Context, req *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// CheckTaskExists calls rpc.BackendService.CheckTaskExists.
func (c *backendServiceClient) CheckTaskExists(ctx context.Context, req *connect.Request[gen.CheckTaskExistsRequest]) (*connect.Response[gen.CheckTaskExistsResponse], error) {
	return c.checkTaskExists.CallUnary(ctx, req)
}

// TryBecomeLeader calls rpc.BackendService.TryBecomeLeader.
func (c *backendServiceClient) TryBecomeLeader(ctx context.Context, req *connect.Request[gen.TryBecomeLeaderRequest]) (*connect.Response[gen.TryBecomeLeaderResponse], error) {
	return c.tryBecomeLeader.CallUnary(ctx, req)
}

// RenewLeadership calls rpc.BackendService.RenewLeadership.
func (c *backendServiceClient) RenewLeadership(ctx context.Context, req *connect.Request[gen.RenewLeadershipRequest]) (*connect.Response[gen.RenewLeadershipResponse], error) {
	return c.renewLeadership.CallUnary(ctx, req)
}

// ReleaseLeadership calls rpc.BackendService.ReleaseLeadership.
func (c *backendServiceClient) ReleaseLeadership(ctx context.Context, req *connect.Request[gen.ReleaseLeadershipRequest]) (*connect.Response[gen.ReleaseLeadershipResponse], error) {
	return c.releaseLeadership.CallUnary(ctx, req)
}

// GetLeader calls rpc.BackendService.GetLeader.
func (c *backendServiceClient) GetLeader(ctx context.Context, req *connect.Request[gen.GetLeaderRequest]) (*connect.Response[gen.GetLeaderResponse], error) {
	return c.getLeader.CallUnary(ctx, req)
}

// ListServers calls rpc.BackendService.ListServers.
func (c *backendServiceClient) ListServers(ctx context.Context, req *connect.Request[gen.ListServersRequest]) (*connect.Response[gen.ListServersResponse], error) {
	return c.listServers.CallUnary(ctx, req)
}

// GetServerById calls rpc.BackendService.GetServerById.
func (c *backendServiceClient) GetServerById(ctx context.Context, req *connect.Request[gen.GetServerByIdRequest]) (*connect.Response[gen.GetServerByIdResponse], error) {
	return c.getServerById.CallUnary(ctx, req)
}

// CreateServer calls rpc.BackendService.CreateServer.
func (c *backendServiceClient) CreateServer(ctx context.Context, req *connect.Request[gen.CreateServerRequest]) (*connect.Response[gen.CreateServerResponse], error) {
	return c.createServer.CallUnary(ctx, req)
}

// UpdateServer calls rpc.BackendService.UpdateServer.
func (c *backendServiceClient) UpdateServer(ctx context.Context, req *connect.Request[gen.UpdateServerRequest]) (*connect.Response[gen.UpdateServerResponse], error) {
	return c.updateServer.CallUnary(ctx, req)
}

// DeleteServer calls rpc.BackendService.DeleteServer.
func (c *backendServiceClient) DeleteServer(ctx context.Context, req *connect.Request[gen.DeleteServerRequest]) (*connect.Response[gen.DeleteServerResponse], error) {
	return c.deleteServer.CallUnary(ctx, req)
}

// ListTasks calls rpc.BackendService.ListTasks.
func (c *backendServiceClient) ListTasks(ctx context.Context, req *connect.Request[gen.ListTasksRequest]) (*connect.Response[gen.ListTasksResponse], error) {
	return c.listTasks.CallUnary(ctx, req)
}

// GetTaskById calls rpc.BackendService.GetTaskById.
func (c *backendServiceClient) GetTaskById(ctx context.Context, req *connect.Request[gen.GetTaskByIdRequest]) (*connect.Response[gen.GetTaskByIdResponse], error) {
	return c.getTaskById.CallUnary(ctx, req)
}

// GetWorkerStats calls rpc.BackendService.GetWorkerStats.
func (c *backendServiceClient) GetWorkerStats(ctx context.Context, req *connect.Request[gen.GetWorkerStatsRequest]) (*connect.Response[gen.GetWorkerStatsResponse], error) {
	return c.getWorkerStats.CallUnary(ctx, req)
}

// HealthCheck calls rpc.BackendService.HealthCheck.
func (c *backendServiceClient) HealthCheck(ctx context.Context, req *connect.Request[gen.HealthCheckRequest]) (*connect.Response[gen.HealthCheckResponse], error) {
	return c.healthCheck.CallUnary(ctx, req)
}

// GetProbeTask calls rpc.BackendService.GetProbeTask.
func (c *backendServiceClient) GetProbeTask(ctx context.Context, req *connect.Request[gen.GetProbeTaskRequest]) (*connect.Response[gen.GetProbeTaskResponse], error) {
	return c.getProbeTask.CallUnary(ctx, req)
}

// ReportProbeResult calls rpc.BackendService.ReportProbeResult.
func (c *backendServiceClient) ReportProbeResult(ctx context.Context, req *connect.Request[gen.ReportProbeResultRequest]) (*connect.Response[gen.ReportProbeResultResponse], error) {
	return c.reportProbeResult.CallUnary(ctx, req)
}

// BackendServiceHandler is an implementation of the rpc.BackendService service.
type BackendServiceHandler interface {
	RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error)
	Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error)
	GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error)
	UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error)
	CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error)
	FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error)
	CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error)
	GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error)
	GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error)
	CheckTaskExists(context.Context, *connect.Request[gen.CheckTaskExistsRequest]) (*connect.Response[gen.CheckTaskExistsResponse], error)
	TryBecomeLeader(context.Context, *connect.Request[gen.TryBecomeLeaderRequest]) (*connect.Response[gen.TryBecomeLeaderResponse], error)
	RenewLeadership(context.Context, *connect.Request[gen.RenewLeadershipRequest]) (*connect.Response[gen.RenewLeadershipResponse], error)
	ReleaseLeadership(context.Context, *connect.Request[gen.ReleaseLeadershipRequest]) (*connect.Response[gen.ReleaseLeadershipResponse], error)
	GetLeader(context.Context, *connect.Request[gen.GetLeaderRequest]) (*connect.Response[gen.GetLeaderResponse], error)
	ListServers(context.Context, *connect.Request[gen.ListServersRequest]) (*connect.Response[gen.ListServersResponse], error)
	GetServerById(context.Context, *connect.Request[gen.GetServerByIdRequest]) (*connect.Response[gen.GetServerByIdResponse], error)
	CreateServer(context.Context, *connect.Request[gen.CreateServerRequest]) (*connect.Response[gen.CreateServerResponse], error)
	UpdateServer(context.Context, *connect.Request[gen.UpdateServerRequest]) (*connect.Response[gen.UpdateServerResponse], error)
	DeleteServer(context.Context, *connect.Request[gen.DeleteServerRequest]) (*connect.Response[gen.DeleteServerResponse], error)
	ListTasks(context.Context, *connect.Request[gen.ListTasksRequest]) (*connect.Response[gen.ListTasksResponse], error)
	GetTaskById(context.Context, *connect.Request[gen.GetTaskByIdRequest]) (*connect.Response[gen.GetTaskByIdResponse], error)
	GetWorkerStats(context.Context, *connect.Request[gen.GetWorkerStatsRequest]) (*connect.Response[gen.GetWorkerStatsResponse], error)
	HealthCheck(context.Context, *connect.Request[gen.HealthCheckRequest]) (*connect.Response[gen.HealthCheckResponse], error)
	GetProbeTask(context.Context, *connect.Request[gen.GetProbeTaskRequest]) (*connect.Response[gen.GetProbeTaskResponse], error)
	ReportProbeResult(context.Context, *connect.Request[gen.ReportProbeResultRequest]) (*connect.Response[gen.ReportProbeResultResponse], error)
}

// NewBackendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackendServiceHandler(svc BackendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backendServiceMethods := gen.File_proto_service_proto.Services().ByName("BackendService").Methods()
	backendServiceRegisterWorkerHandler := connect.NewUnaryHandler(
		BackendServiceRegisterWorkerProcedure,
		svc.RegisterWorker,
		connect.WithSchema(backendServiceMethods.ByName("RegisterWorker")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceHeartbeatHandler := connect.NewUnaryHandler(
		BackendServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(backendServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetTaskHandler := connect.NewUnaryHandler(
		BackendServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(backendServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceUpdateTaskProgressHandler := connect.NewUnaryHandler(
		BackendServiceUpdateTaskProgressProcedure,
		svc.UpdateTaskProgress,
		connect.WithSchema(backendServiceMethods.ByName("UpdateTaskProgress")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCompleteTaskHandler := connect.NewUnaryHandler(
		BackendServiceCompleteTaskProcedure,
		svc.CompleteTask,
		connect.WithSchema(backendServiceMethods.ByName("CompleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceFailTaskHandler := connect.NewUnaryHandler(
		BackendServiceFailTaskProcedure,
		svc.FailTask,
		connect.WithSchema(backendServiceMethods.ByName("FailTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCreateTaskHandler := connect.NewUnaryHandler(
		BackendServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(backendServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetServersHandler := connect.NewUnaryHandler(
		BackendServiceGetServersProcedure,
		svc.GetServers,
		connect.WithSchema(backendServiceMethods.ByName("GetServers")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetServerHandler := connect.NewUnaryHandler(
		BackendServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(backendServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCheckTaskExistsHandler := connect.NewUnaryHandler(
		BackendServiceCheckTaskExistsProcedure,
		svc.CheckTaskExists,
		connect.WithSchema(backendServiceMethods.ByName("CheckTaskExists")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceTryBecomeLeaderHandler := connect.NewUnaryHandler(
		BackendServiceTryBecomeLeaderProcedure,
		svc.TryBecomeLeader,
		connect.WithSchema(backendServiceMethods.ByName("TryBecomeLeader")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceRenewLeadershipHandler := connect.NewUnaryHandler(
		BackendServiceRenewLeadershipProcedure,
		svc.RenewLeadership,
		connect.WithSchema(backendServiceMethods.ByName("RenewLeadership")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceReleaseLeadershipHandler := connect.NewUnaryHandler(
		BackendServiceReleaseLeadershipProcedure,
		svc.ReleaseLeadership,
		connect.WithSchema(backendServiceMethods.ByName("ReleaseLeadership")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetLeaderHandler := connect.NewUnaryHandler(
		BackendServiceGetLeaderProcedure,
		svc.GetLeader,
		connect.WithSchema(backendServiceMethods.ByName("GetLeader")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceListServersHandler := connect.NewUnaryHandler(
		BackendServiceListServersProcedure,
		svc.ListServers,
		connect.WithSchema(backendServiceMethods.ByName("ListServers")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetServerByIdHandler := connect.NewUnaryHandler(
		BackendServiceGetServerByIdProcedure,
		svc.GetServerById,
		connect.WithSchema(backendServiceMethods.ByName("GetServerById")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCreateServerHandler := connect.NewUnaryHandler(
		BackendServiceCreateServerProcedure,
		svc.CreateServer,
		connect.WithSchema(backendServiceMethods.ByName("CreateServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceUpdateServerHandler := connect.NewUnaryHandler(
		BackendServiceUpdateServerProcedure,
		svc.UpdateServer,
		connect.WithSchema(backendServiceMethods.ByName("UpdateServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceDeleteServerHandler := connect.NewUnaryHandler(
		BackendServiceDeleteServerProcedure,
		svc.DeleteServer,
		connect.WithSchema(backendServiceMethods.ByName("DeleteServer")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceListTasksHandler := connect.NewUnaryHandler(
		BackendServiceListTasksProcedure,
		svc.ListTasks,
		connect.WithSchema(backendServiceMethods.ByName("ListTasks")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetTaskByIdHandler := connect.NewUnaryHandler(
		BackendServiceGetTaskByIdProcedure,
		svc.GetTaskById,
		connect.WithSchema(backendServiceMethods.ByName("GetTaskById")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetWorkerStatsHandler := connect.NewUnaryHandler(
		BackendServiceGetWorkerStatsProcedure,
		svc.GetWorkerStats,
		connect.WithSchema(backendServiceMethods.ByName("GetWorkerStats")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceHealthCheckHandler := connect.NewUnaryHandler(
		BackendServiceHealthCheckProcedure,
		svc.HealthCheck,
		connect.WithSchema(backendServiceMethods.ByName("HealthCheck")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetProbeTaskHandler := connect.NewUnaryHandler(
		BackendServiceGetProbeTaskProcedure,
		svc.GetProbeTask,
		connect.WithSchema(backendServiceMethods.ByName("GetProbeTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceReportProbeResultHandler := connect.NewUnaryHandler(
		BackendServiceReportProbeResultProcedure,
		svc.ReportProbeResult,
		connect.WithSchema(backendServiceMethods.ByName("ReportProbeResult")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.BackendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackendServiceRegisterWorkerProcedure:
			backendServiceRegisterWorkerHandler.ServeHTTP(w, r)
		case BackendServiceHeartbeatProcedure:
			backendServiceHeartbeatHandler.ServeHTTP(w, r)
		case BackendServiceGetTaskProcedure:
			backendServiceGetTaskHandler.ServeHTTP(w, r)
		case BackendServiceUpdateTaskProgressProcedure:
			backendServiceUpdateTaskProgressHandler.ServeHTTP(w, r)
		case BackendServiceCompleteTaskProcedure:
			backendServiceCompleteTaskHandler.ServeHTTP(w, r)
		case BackendServiceFailTaskProcedure:
			backendServiceFailTaskHandler.ServeHTTP(w, r)
		case BackendServiceCreateTaskProcedure:
			backendServiceCreateTaskHandler.ServeHTTP(w, r)
		case BackendServiceGetServersProcedure:
			backendServiceGetServersHandler.ServeHTTP(w, r)
		case BackendServiceGetServerProcedure:
			backendServiceGetServerHandler.ServeHTTP(w, r)
		case BackendServiceCheckTaskExistsProcedure:
			backendServiceCheckTaskExistsHandler.ServeHTTP(w, r)
		case BackendServiceTryBecomeLeaderProcedure:
			backendServiceTryBecomeLeaderHandler.ServeHTTP(w, r)
		case BackendServiceRenewLeadershipProcedure:
			backendServiceRenewLeadershipHandler.ServeHTTP(w, r)
		case BackendServiceReleaseLeadershipProcedure:
			backendServiceReleaseLeadershipHandler.ServeHTTP(w, r)
		case BackendServiceGetLeaderProcedure:
			backendServiceGetLeaderHandler.ServeHTTP(w, r)
		case BackendServiceListServersProcedure:
			backendServiceListServersHandler.ServeHTTP(w, r)
		case BackendServiceGetServerByIdProcedure:
			backendServiceGetServerByIdHandler.ServeHTTP(w, r)
		case BackendServiceCreateServerProcedure:
			backendServiceCreateServerHandler.ServeHTTP(w, r)
		case BackendServiceUpdateServerProcedure:
			backendServiceUpdateServerHandler.ServeHTTP(w, r)
		case BackendServiceDeleteServerProcedure:
			backendServiceDeleteServerHandler.ServeHTTP(w, r)
		case BackendServiceListTasksProcedure:
			backendServiceListTasksHandler.ServeHTTP(w, r)
		case BackendServiceGetTaskByIdProcedure:
			backendServiceGetTaskByIdHandler.ServeHTTP(w, r)
		case BackendServiceGetWorkerStatsProcedure:
			backendServiceGetWorkerStatsHandler.ServeHTTP(w, r)
		case BackendServiceHealthCheckProcedure:
			backendServiceHealthCheckHandler.ServeHTTP(w, r)
		case BackendServiceGetProbeTaskProcedure:
			backendServiceGetProbeTaskHandler.ServeHTTP(w, r)
		case BackendServiceReportProbeResultProcedure:
			backendServiceReportProbeResultHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackendServiceHandler struct{}

func (UnimplementedBackendServiceHandler) RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.RegisterWorker is not implemented"))
}

func (UnimplementedBackendServiceHandler) Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.Heartbeat is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.UpdateTaskProgress is not implemented"))
}

func (UnimplementedBackendServiceHandler) CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CompleteTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.FailTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CreateTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetServers is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) CheckTaskExists(context.Context, *connect.Request[gen.CheckTaskExistsRequest]) (*connect.Response[gen.CheckTaskExistsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CheckTaskExists is not implemented"))
}

func (UnimplementedBackendServiceHandler) TryBecomeLeader(context.Context, *connect.Request[gen.TryBecomeLeaderRequest]) (*connect.Response[gen.TryBecomeLeaderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.TryBecomeLeader is not implemented"))
}

func (UnimplementedBackendServiceHandler) RenewLeadership(context.Context, *connect.Request[gen.RenewLeadershipRequest]) (*connect.Response[gen.RenewLeadershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.RenewLeadership is not implemented"))
}

func (UnimplementedBackendServiceHandler) ReleaseLeadership(context.Context, *connect.Request[gen.ReleaseLeadershipRequest]) (*connect.Response[gen.ReleaseLeadershipResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.ReleaseLeadership is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetLeader(context.Context, *connect.Request[gen.GetLeaderRequest]) (*connect.Response[gen.GetLeaderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetLeader is not implemented"))
}

func (UnimplementedBackendServiceHandler) ListServers(context.Context, *connect.Request[gen.ListServersRequest]) (*connect.Response[gen.ListServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.ListServers is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetServerById(context.Context, *connect.Request[gen.GetServerByIdRequest]) (*connect.Response[gen.GetServerByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetServerById is not implemented"))
}

func (UnimplementedBackendServiceHandler) CreateServer(context.Context, *connect.Request[gen.CreateServerRequest]) (*connect.Response[gen.CreateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CreateServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) UpdateServer(context.Context, *connect.Request[gen.UpdateServerRequest]) (*connect.Response[gen.UpdateServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.UpdateServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) DeleteServer(context.Context, *connect.Request[gen.DeleteServerRequest]) (*connect.Response[gen.DeleteServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.DeleteServer is not implemented"))
}

func (UnimplementedBackendServiceHandler) ListTasks(context.Context, *connect.Request[gen.ListTasksRequest]) (*connect.Response[gen.ListTasksResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.ListTasks is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetTaskById(context.Context, *connect.Request[gen.GetTaskByIdRequest]) (*connect.Response[gen.GetTaskByIdResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetTaskById is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetWorkerStats(context.Context, *connect.Request[gen.GetWorkerStatsRequest]) (*connect.Response[gen.GetWorkerStatsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetWorkerStats is not implemented"))
}

func (UnimplementedBackendServiceHandler) HealthCheck(context.Context, *connect.Request[gen.HealthCheckRequest]) (*connect.Response[gen.HealthCheckResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.HealthCheck is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetProbeTask(context.Context, *connect.Request[gen.GetProbeTaskRequest]) (*connect.Response[gen.GetProbeTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetProbeTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) ReportProbeResult(context.Context, *connect.Request[gen.ReportProbeResultRequest]) (*connect.Response[gen.ReportProbeResultResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.ReportProbeResult is not implemented"))
}
