// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: proto/service.proto

package genconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	gen "github.com/Meedoeed/ssh-sync-automation/internal/gen"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BackendServiceName is the fully-qualified name of the BackendService service.
	BackendServiceName = "rpc.BackendService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BackendServiceRegisterWorkerProcedure is the fully-qualified name of the BackendService's
	// RegisterWorker RPC.
	BackendServiceRegisterWorkerProcedure = "/rpc.BackendService/RegisterWorker"
	// BackendServiceHeartbeatProcedure is the fully-qualified name of the BackendService's Heartbeat
	// RPC.
	BackendServiceHeartbeatProcedure = "/rpc.BackendService/Heartbeat"
	// BackendServiceGetTaskProcedure is the fully-qualified name of the BackendService's GetTask RPC.
	BackendServiceGetTaskProcedure = "/rpc.BackendService/GetTask"
	// BackendServiceUpdateTaskProgressProcedure is the fully-qualified name of the BackendService's
	// UpdateTaskProgress RPC.
	BackendServiceUpdateTaskProgressProcedure = "/rpc.BackendService/UpdateTaskProgress"
	// BackendServiceCompleteTaskProcedure is the fully-qualified name of the BackendService's
	// CompleteTask RPC.
	BackendServiceCompleteTaskProcedure = "/rpc.BackendService/CompleteTask"
	// BackendServiceFailTaskProcedure is the fully-qualified name of the BackendService's FailTask RPC.
	BackendServiceFailTaskProcedure = "/rpc.BackendService/FailTask"
	// BackendServiceCreateTaskProcedure is the fully-qualified name of the BackendService's CreateTask
	// RPC.
	BackendServiceCreateTaskProcedure = "/rpc.BackendService/CreateTask"
	// BackendServiceGetServersProcedure is the fully-qualified name of the BackendService's GetServers
	// RPC.
	BackendServiceGetServersProcedure = "/rpc.BackendService/GetServers"
	// BackendServiceGetServerProcedure is the fully-qualified name of the BackendService's GetServer
	// RPC.
	BackendServiceGetServerProcedure = "/rpc.BackendService/GetServer"
)

// BackendServiceClient is a client for the rpc.BackendService service.
type BackendServiceClient interface {
	// Worker регистрация и управление
	RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error)
	Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error)
	// Задачи
	GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error)
	UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error)
	CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error)
	FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error)
	// Управление задачами (для шедулера)
	CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error)
	// Информация о серверах (для шедулера и воркера)
	GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error)
	GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error)
}

// NewBackendServiceClient constructs a client for the rpc.BackendService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBackendServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BackendServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	backendServiceMethods := gen.File_proto_service_proto.Services().ByName("BackendService").Methods()
	return &backendServiceClient{
		registerWorker: connect.NewClient[gen.RegisterWorkerRequest, gen.RegisterWorkerResponse](
			httpClient,
			baseURL+BackendServiceRegisterWorkerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("RegisterWorker")),
			connect.WithClientOptions(opts...),
		),
		heartbeat: connect.NewClient[gen.HeartbeatRequest, gen.HeartbeatResponse](
			httpClient,
			baseURL+BackendServiceHeartbeatProcedure,
			connect.WithSchema(backendServiceMethods.ByName("Heartbeat")),
			connect.WithClientOptions(opts...),
		),
		getTask: connect.NewClient[gen.GetTaskRequest, gen.GetTaskResponse](
			httpClient,
			baseURL+BackendServiceGetTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetTask")),
			connect.WithClientOptions(opts...),
		),
		updateTaskProgress: connect.NewClient[gen.UpdateProgressRequest, gen.UpdateProgressResponse](
			httpClient,
			baseURL+BackendServiceUpdateTaskProgressProcedure,
			connect.WithSchema(backendServiceMethods.ByName("UpdateTaskProgress")),
			connect.WithClientOptions(opts...),
		),
		completeTask: connect.NewClient[gen.CompleteTaskRequest, gen.CompleteTaskResponse](
			httpClient,
			baseURL+BackendServiceCompleteTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CompleteTask")),
			connect.WithClientOptions(opts...),
		),
		failTask: connect.NewClient[gen.FailTaskRequest, gen.FailTaskResponse](
			httpClient,
			baseURL+BackendServiceFailTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("FailTask")),
			connect.WithClientOptions(opts...),
		),
		createTask: connect.NewClient[gen.CreateTaskRequest, gen.CreateTaskResponse](
			httpClient,
			baseURL+BackendServiceCreateTaskProcedure,
			connect.WithSchema(backendServiceMethods.ByName("CreateTask")),
			connect.WithClientOptions(opts...),
		),
		getServers: connect.NewClient[gen.GetServersRequest, gen.GetServersResponse](
			httpClient,
			baseURL+BackendServiceGetServersProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetServers")),
			connect.WithClientOptions(opts...),
		),
		getServer: connect.NewClient[gen.GetServerRequest, gen.GetServerResponse](
			httpClient,
			baseURL+BackendServiceGetServerProcedure,
			connect.WithSchema(backendServiceMethods.ByName("GetServer")),
			connect.WithClientOptions(opts...),
		),
	}
}

// backendServiceClient implements BackendServiceClient.
type backendServiceClient struct {
	registerWorker     *connect.Client[gen.RegisterWorkerRequest, gen.RegisterWorkerResponse]
	heartbeat          *connect.Client[gen.HeartbeatRequest, gen.HeartbeatResponse]
	getTask            *connect.Client[gen.GetTaskRequest, gen.GetTaskResponse]
	updateTaskProgress *connect.Client[gen.UpdateProgressRequest, gen.UpdateProgressResponse]
	completeTask       *connect.Client[gen.CompleteTaskRequest, gen.CompleteTaskResponse]
	failTask           *connect.Client[gen.FailTaskRequest, gen.FailTaskResponse]
	createTask         *connect.Client[gen.CreateTaskRequest, gen.CreateTaskResponse]
	getServers         *connect.Client[gen.GetServersRequest, gen.GetServersResponse]
	getServer          *connect.Client[gen.GetServerRequest, gen.GetServerResponse]
}

// RegisterWorker calls rpc.BackendService.RegisterWorker.
func (c *backendServiceClient) RegisterWorker(ctx context.Context, req *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error) {
	return c.registerWorker.CallUnary(ctx, req)
}

// Heartbeat calls rpc.BackendService.Heartbeat.
func (c *backendServiceClient) Heartbeat(ctx context.Context, req *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error) {
	return c.heartbeat.CallUnary(ctx, req)
}

// GetTask calls rpc.BackendService.GetTask.
func (c *backendServiceClient) GetTask(ctx context.Context, req *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error) {
	return c.getTask.CallUnary(ctx, req)
}

// UpdateTaskProgress calls rpc.BackendService.UpdateTaskProgress.
func (c *backendServiceClient) UpdateTaskProgress(ctx context.Context, req *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error) {
	return c.updateTaskProgress.CallUnary(ctx, req)
}

// CompleteTask calls rpc.BackendService.CompleteTask.
func (c *backendServiceClient) CompleteTask(ctx context.Context, req *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error) {
	return c.completeTask.CallUnary(ctx, req)
}

// FailTask calls rpc.BackendService.FailTask.
func (c *backendServiceClient) FailTask(ctx context.Context, req *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error) {
	return c.failTask.CallUnary(ctx, req)
}

// CreateTask calls rpc.BackendService.CreateTask.
func (c *backendServiceClient) CreateTask(ctx context.Context, req *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error) {
	return c.createTask.CallUnary(ctx, req)
}

// GetServers calls rpc.BackendService.GetServers.
func (c *backendServiceClient) GetServers(ctx context.Context, req *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error) {
	return c.getServers.CallUnary(ctx, req)
}

// GetServer calls rpc.BackendService.GetServer.
func (c *backendServiceClient) GetServer(ctx context.Context, req *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error) {
	return c.getServer.CallUnary(ctx, req)
}

// BackendServiceHandler is an implementation of the rpc.BackendService service.
type BackendServiceHandler interface {
	// Worker регистрация и управление
	RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error)
	Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error)
	// Задачи
	GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error)
	UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error)
	CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error)
	FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error)
	// Управление задачами (для шедулера)
	CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error)
	// Информация о серверах (для шедулера и воркера)
	GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error)
	GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error)
}

// NewBackendServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBackendServiceHandler(svc BackendServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	backendServiceMethods := gen.File_proto_service_proto.Services().ByName("BackendService").Methods()
	backendServiceRegisterWorkerHandler := connect.NewUnaryHandler(
		BackendServiceRegisterWorkerProcedure,
		svc.RegisterWorker,
		connect.WithSchema(backendServiceMethods.ByName("RegisterWorker")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceHeartbeatHandler := connect.NewUnaryHandler(
		BackendServiceHeartbeatProcedure,
		svc.Heartbeat,
		connect.WithSchema(backendServiceMethods.ByName("Heartbeat")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetTaskHandler := connect.NewUnaryHandler(
		BackendServiceGetTaskProcedure,
		svc.GetTask,
		connect.WithSchema(backendServiceMethods.ByName("GetTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceUpdateTaskProgressHandler := connect.NewUnaryHandler(
		BackendServiceUpdateTaskProgressProcedure,
		svc.UpdateTaskProgress,
		connect.WithSchema(backendServiceMethods.ByName("UpdateTaskProgress")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCompleteTaskHandler := connect.NewUnaryHandler(
		BackendServiceCompleteTaskProcedure,
		svc.CompleteTask,
		connect.WithSchema(backendServiceMethods.ByName("CompleteTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceFailTaskHandler := connect.NewUnaryHandler(
		BackendServiceFailTaskProcedure,
		svc.FailTask,
		connect.WithSchema(backendServiceMethods.ByName("FailTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceCreateTaskHandler := connect.NewUnaryHandler(
		BackendServiceCreateTaskProcedure,
		svc.CreateTask,
		connect.WithSchema(backendServiceMethods.ByName("CreateTask")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetServersHandler := connect.NewUnaryHandler(
		BackendServiceGetServersProcedure,
		svc.GetServers,
		connect.WithSchema(backendServiceMethods.ByName("GetServers")),
		connect.WithHandlerOptions(opts...),
	)
	backendServiceGetServerHandler := connect.NewUnaryHandler(
		BackendServiceGetServerProcedure,
		svc.GetServer,
		connect.WithSchema(backendServiceMethods.ByName("GetServer")),
		connect.WithHandlerOptions(opts...),
	)
	return "/rpc.BackendService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BackendServiceRegisterWorkerProcedure:
			backendServiceRegisterWorkerHandler.ServeHTTP(w, r)
		case BackendServiceHeartbeatProcedure:
			backendServiceHeartbeatHandler.ServeHTTP(w, r)
		case BackendServiceGetTaskProcedure:
			backendServiceGetTaskHandler.ServeHTTP(w, r)
		case BackendServiceUpdateTaskProgressProcedure:
			backendServiceUpdateTaskProgressHandler.ServeHTTP(w, r)
		case BackendServiceCompleteTaskProcedure:
			backendServiceCompleteTaskHandler.ServeHTTP(w, r)
		case BackendServiceFailTaskProcedure:
			backendServiceFailTaskHandler.ServeHTTP(w, r)
		case BackendServiceCreateTaskProcedure:
			backendServiceCreateTaskHandler.ServeHTTP(w, r)
		case BackendServiceGetServersProcedure:
			backendServiceGetServersHandler.ServeHTTP(w, r)
		case BackendServiceGetServerProcedure:
			backendServiceGetServerHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBackendServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBackendServiceHandler struct{}

func (UnimplementedBackendServiceHandler) RegisterWorker(context.Context, *connect.Request[gen.RegisterWorkerRequest]) (*connect.Response[gen.RegisterWorkerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.RegisterWorker is not implemented"))
}

func (UnimplementedBackendServiceHandler) Heartbeat(context.Context, *connect.Request[gen.HeartbeatRequest]) (*connect.Response[gen.HeartbeatResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.Heartbeat is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetTask(context.Context, *connect.Request[gen.GetTaskRequest]) (*connect.Response[gen.GetTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) UpdateTaskProgress(context.Context, *connect.Request[gen.UpdateProgressRequest]) (*connect.Response[gen.UpdateProgressResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.UpdateTaskProgress is not implemented"))
}

func (UnimplementedBackendServiceHandler) CompleteTask(context.Context, *connect.Request[gen.CompleteTaskRequest]) (*connect.Response[gen.CompleteTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CompleteTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) FailTask(context.Context, *connect.Request[gen.FailTaskRequest]) (*connect.Response[gen.FailTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.FailTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) CreateTask(context.Context, *connect.Request[gen.CreateTaskRequest]) (*connect.Response[gen.CreateTaskResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.CreateTask is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetServers(context.Context, *connect.Request[gen.GetServersRequest]) (*connect.Response[gen.GetServersResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetServers is not implemented"))
}

func (UnimplementedBackendServiceHandler) GetServer(context.Context, *connect.Request[gen.GetServerRequest]) (*connect.Response[gen.GetServerResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("rpc.BackendService.GetServer is not implemented"))
}
